StoneStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoneStore.Domain.Abstract;

namespace StoneStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController (IProductRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products.Select(x => x.category).Distinct().OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

StoneStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoneStore.Domain.Abstract;
using StoneStore.WebUI.Models;
using StoneStore.Domain.Entities;

namespace StoneStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository myrepository;

        public ProductController (IProductRepository productRepository)
        {
            this.myrepository = productRepository;
        }

        public int PageSize = 5;
        public ViewResult List(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = myrepository.Products.Where(p => category == null || p.category == category).OrderBy(p => p.ProductID).Skip((page - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    //TotalItems = myrepository.Products.Count()

                    TotalItems = category == null ?
                                 myrepository.Products.Count() :
                                 myrepository.Products.Where
                                    (e => e.category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = myrepository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

StoneStore.WebUI/Views/Shared/ProductSummary.cshtml
@model StoneStore.Domain.Entities.Product

<style>
    body, .row {
        background-color: silver;
    }
</style>

<div class="col-sm-5" style="align-content:center;">
    <div class="row" style="margin:4px 4px 4px 4px">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75" src="@Url.Action("GetImage", "Product", new {Model.ProductID})" />
            </div>
        }
        <h3>
            <strong>@Model.Name</strong>   
            By<strong>&nbsp;@Model.Company</strong>
        </h3>
        <h5>
            Type:<b>&nbsp;@Model.category</b>
        </h5>
        <h6>           
            <span class="lead text-center">@Model.Description</span>
        </h6>
        
        <span class="text-center label label-primary">
            @Model.Price.ToString("c")/per tile
        </span>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="center-block">
                @Html.HiddenFor(x => x.ProductID)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

                <input type="submit" class="btn btn-success" value="Add to cart" />
            </div>
        }
        
    </div>
</div>

StoneStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>
</body>
</html>

StoneStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    
    
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">STONE STORE</a>
        @Html.Action("Summary", "Cart")
    </div>

    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>

        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>

    
</body>
</html>